apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cortxcontrol.localpathpvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: localfs
  resources:
    requests:
      storage: {{ .Values.cortxcontrol.localpathpvc.requeststoragesize }}
