apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cortxclient.localpathpvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.cortxclient.localpathpvc.storageclassname }}
  resources:
    requests:
      storage: {{ .Values.cortxclient.localpathpvc.requeststoragesize }}
