apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ssc-vm-g2-rhev4-1988.colo.seagate.com
          - ssc-vm-g2-rhev4-1989.colo.seagate.com
          - ssc-vm-g2-rhev4-2367.colo.seagate.com
          - ssc-vm-g2-rhev4-2368.colo.seagate.com
  storageClassDevices:
    - storageClassName: "localblock"
      volumeMode: Block 
      devicePaths:
        - /dev/sdc
        - /dev/sdd
        - /dev/sde
        - /dev/sdf
    - storageClassName: "localfs"
      volumeMode: Filesystem
      fsType: ext4
      devicePaths:
        - /dev/sdg1
        - /dev/sdg2
        - /dev/sdg3
        - /dev/sdg4
        - /dev/sdg5
        - /dev/sdg6
        - /dev/sdg7